name: CI
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy to Hetzner
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/deploy.key
          chmod 600 ~/.ssh/deploy.key
          cat >>~/.ssh/config <<END
          Host deploy
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/deploy.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}

      - name: Stop the server
        run: ssh deploy 'sudo systemctl stop cali-circuit'

      - name: Check out the source
        run: ssh deploy 'cd /var/www/cali-circuit && git pull'

      - name: Start the server
        if: ${{ always() }}
        run: ssh deploy 'sudo systemctl start cali-circuit'
